### ISSUE TITLE
Runaway exception

### ISSUE THREAD

**Issue by pvm255** [NeblioTeam/NEBL-Pi#3]
A fatal error occurred. neblio can no longer continue safely and will quit.

EXCEPTION: St13runtime_error       
init_blockindex(): error opening database environment Corruption: no meta-nextfile entry in descriptor       
neblio in Runaway exception

This is happening when I run the neblio-qt wallet from the raspberry pi 3 i'm running the latest version of the neblio wallet.It was running fine until recently but now it pops this error

**Comment by Crypt0daz** [comment]
Not sure how to create a link to it so copying from #24 on Windows wallet folder. Solution given by Eddy (edited location to Linux location)

Forcibly closing the database that stores the blockchain, due to a crash or other issue, can of course lead to the database becoming corrupt.
On Linux the default location is ~/.neblio/ (i presume Pi is the same)
To resolve this issue, shut down neblio.
Delete all files in that directory EXCEPT FOR WALLET.DAT
Restart neblio and it will download a fresh copy of the blockchain.
Adding an option to do this automatically could be done, but it is a pretty rare thing to happen.

**Comment by pvm255** [comment]
Thank you  @Crypt0daz  works fine now
