### ISSUE TITLE
RPi Hardware requirements for staking

### ISSUE THREAD

**Issue by Chiqui1234ok** [NeblioTeam/NEBL-Pi#7]
Hi. You guys are sure about NEBL staking on Raspberry Pi 3B on 2021? The question is because other "light" cryptos doesn't work well without SSD, at least 4GB of RAM and low-to-mid range x86 processor (like Core i3 7100).

Thanks for your answers!

**Comment by nebliodev** [comment]
Pi3B will have problems, due to its limited RAM, running Neblio Core v3.2.0. We recommend the Pi4, most users buy the 4GB model. 

However, we are working on reducing the RAM requirements of Neblio Core by removing the in-memory block index. In a future version, we expect Neblio Core to run again on devices with less than 1GB of RAM, such as the Pi3 series and others. Keep a watch on the release changelogs if this is something you are looking for.

**Comment by Chiqui1234ok** [comment]
> 
> 
> Pi3B will have problems, due to its limited RAM, running Neblio Core v3.2.0. We recommend the Pi4, most users buy the 4GB model.
> 
> However, we are working on reducing the RAM requirements of Neblio Core by removing the in-memory block index. In a future version, we expect Neblio Core to run again on devices with less than 1GB of RAM, such as the Pi3 series and others. Keep a watch on the release changelogs if this is something you are looking for.

Thanks for your reply. This feature is on roadmap or has a finish date? Thanks :D
